#!/usr/bin/env bash
quotes=(
    "Take Your Heart!"
    "Steal Your Heart!"
    "You'll never see it coming."
    "The show's about to start."
    "Time to make them confess."
    "I am thou, thou art I."
    "No escape from reality."
    "Time to wake up to the truth."
    "Our hearts are filled with rebellion."
    "Show's over!"
    "Checkmate."
    "You can't escape!"
    "Persona!"
    "Life will change."
    "Welcome to the Velvet Room."
    "We are the Phantom Thieves of Hearts."
    "Justice will prevail."
    "Reveal yourself!"
    "It's showtime!"
    "All-Out Attack!"
    "Seize the moment! Live with no regrets!"
    "Your move."
    "Time to break out!"
)
echo "${quotes[$RANDOM % ${#quotes[@]}]}"
